[target.x86_64-unknown-linux-gnu]
image.name = "eva-videosink-build-x86_64:latest"
image.toolchain = ["x86_64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu]
image.name = "eva-videosink-build-aarch64:latest"
image.toolchain = ["x86_64-unknown-linux-gnu"]
