all:
  @echo "Select target"

prepare:
  docker build -f Dockerfile.x86_64 -t eva-videosink-build-x86_64:latest .
  docker build -f Dockerfile.aarch64 -t eva-videosink-build-aarch64:latest .

build-x86_64:
  cross build --target x86_64-unknown-linux-gnu --release --features openssl-vendored

build-aarch64:
  cross build --target aarch64-unknown-linux-gnu --release --features openssl-vendored
