[package]
name = "eva-gst-pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
async-trait = "0.1"
eva-common = { version = "0.3.113", features = ["events", "common-payloads", "payload", "acl", "multimedia"] }
eva-sdk = { version = "0.3", features = ["controller"] }
gstreamer = { version = "0.22" }
gstreamer-app = "0.22"
log = "0.4"
mimalloc = "0.1"
once_cell = "1.20"
serde = { version = "1.0", features = ["derive", "rc"] }
tokio = { version = "1.36", features = ["full"] }

[features]
std-alloc = []
