[package]
name = "eva-filemgr"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
eva-common = { features = ["events", "time"] , workspace = true }
eva-sdk = { features = ["http", "fs"] , workspace = true }
tokio = { features = ["full"] , workspace = true }
async-trait = { workspace = true }
serde = { features = ["derive", "rc"] , workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
async-channel = { workspace = true }
serde_yaml = { workspace = true }
hex = { workspace = true }
parse_int = "0.6.0"
mimalloc = { workspace = true }
tempfile = "3.10.0"
bmart = { workspace = true }
openssl = { workspace = true }
glob-match = "0.2.1"
async-recursion = { workspace = true }
uuid = { workspace = true }
termios = "0.3.3"
libc = "0.2.169"

[features]
std-alloc = []
openssl-vendored = ["openssl/vendored"]
