#!/bin/sh

ARCHS="aarch64-musl x86_64-musl x86_64-ubuntu20.04"
RUST_VER_REQUIRED="1.90.0"

export RUST_VER_REQUIRED

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install v20.7.0
nvm use v20.7.0
npm config set fund false

[ -d /build/eva4 ] && export BUILD_DIR=/build

./dev/make-vendored-apps || exit 1

if [ ! "$UPLOAD_ONLY" ]; then
  for arch in ${ARCHS}; do
    MASTER=$MASTER ./dev/make-dist "$arch" || exit 1
  done
  ./dev/create-manifest "${ARCHS}" || exit 1
fi

if [ ! "$BUILD_ONLY" ]; then
  for arch in ${ARCHS}; do
    ./dev/upload-dist "$arch" || exit 1
  done
  ./dev/upload-update || exit 1
  ./dev/upload-manifest || exit 1
  ./dev/upload-changelog || exit 1
fi
