#!/bin/sh

CURDIR=$(pwd)

RSATOOL="$CURDIR/dev/rsatool"

[ -z "${BUILD_DIR}" ] && BUILD_DIR=/tdata/_eva4_build
cd "${BUILD_DIR}/eva4" || exit 1

VERSION=$(grep ^version Cargo.toml|cut -d \" -f2)
BUILD=$(grep const\ BUILD eva/src/lib.rs|cut -d= -f2|cut -d\; -f1|awk '{ print $1 }')

cd ..

"${CURDIR}/dev/mgen.py" --version "${VERSION}" --build "${BUILD}" \
  --rsa-tool "$RSATOOL" --key-dir "${CURDIR}/.keys" --archs "$1" \
  --output "manifest-${BUILD}.json" || exit 1
