#!/bin/sh

ARCH=$1

[ -z "${BUILD_DIR}" ] && BUILD_DIR=/tdata/_eva4_build
cd "${BUILD_DIR}/eva4" || exit 1

VERSION=$(grep ^version Cargo.toml|cut -d \" -f2)
BUILD=$(grep const\ BUILD eva/src/lib.rs|cut -d= -f2|cut -d\; -f1|awk '{ print $1 }')
DISTRO="eva-${VERSION}-${BUILD}-${ARCH}.tgz"
URI=pub.bma.ai/eva4/${VERSION}/nightly

cd ..

echo "Uploading ${DISTRO}..."
gsutil cp -a public-read "${DISTRO}" "gs://${URI}/"
