#!/bin/sh

[ -z "${BUILD_DIR}" ] && BUILD_DIR=/tdata/_eva4_build
cd "${BUILD_DIR}/eva4" || exit 1

BUILD=$(grep const\ BUILD eva/src/lib.rs|cut -d= -f2|cut -d\; -f1|awk '{ print $1 }')
VERSION=$(grep ^version Cargo.toml|cut -d \" -f2)
URI=pub.bma.ai/eva4/${VERSION}/nightly

gsutil -h "Content-Type:text/x-shellscript" cp -a public-read \
  update.sh "gs://${URI}/update-${BUILD}.sh" || exit 1
gsutil -h "Content-Type:text/x-rst" cp -a public-read UPDATE.rst "gs://${URI}/" || exit 1
