VERSION := `grep ^version Cargo.toml|cut -d\" -f2`

run-sink: build-release run-launch-sink

run-src: build-release run-launch-src

inspect-sink: build-release run-inspect-sink

inspect-src: build-release run-inspect-source

release: build-x86_64 build-aarch64 upload

upload:
  gsutil cp -a public-read ../target/aarch64-unknown-linux-gnu/release/libgsteva.so gs://pub.bma.ai/eva-gst/libgsteva-{{ VERSION }}-aarch64.so
  gsutil cp -a public-read ../target/x86_64-unknown-linux-gnu/release/libgsteva.so gs://pub.bma.ai/eva-gst/libgsteva-{{ VERSION }}-x86_64.so
  rci job run pub.bma.ai

build-release:
  cargo build --release

run-launch-sink:
  GST_PLUGIN_PATH=../target/release gst-launch-1.0 -v videotestsrc ! 'video/x-raw,width=1280,height=720' ! videoconvert ! openh264enc ! evasink oid=lvar:video/stream1

run-launch-src:
  GST_PLUGIN_PATH=../target/release gst-launch-1.0 -v evasrc oid=lvar:video/stream1 ! openh264dec ! fpsdisplaysink

run-inspect-sink:
  GST_PLUGIN_PATH=../target/release gst-inspect-1.0 evasink

run-inspect-source:
  GST_PLUGIN_PATH=../target/release gst-inspect-1.0 evasrc

build-x86_64:
  cross build --target x86_64-unknown-linux-gnu --release

build-aarch64:
  cross build --target aarch64-unknown-linux-gnu --release
