#!/usr/bin/env bash

cd /opt/eva4 || exit 1

# mount external dirs
EXTERNAL_DIRS="runtime log"
for dir in $EXTERNAL_DIRS; do
  if [ -d "/$dir" ]; then
    rm -rf "$dir"
    ln -sf "/$dir" "/opt/eva4/$dir" || exit 1
  fi
done

# prepare if the registry is not initialized
if [ ! -d ./runtime/registry ]; then
  ./prepare || exit 2
fi

# run update if not initialized
if [ -f ./update.sh ]; then
  bash ./update.sh || exit 3
  rm -f update.sh prepare
  rmdir log > /dev/null 2>&1
fi

./sbin/eva-control launch
