[package]
name = "logreducer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
ttl_cache = { workspace = true }
