[package]
name = "tracing-async-mutex"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
tokio = { workspace = true, features = ["sync"] }
